### ISSUE TITLE
Issue on composer require

### ISSUE THREAD

**Issue by alexJouni** [zepgram/module-multi-threading#2]
Hello Benjamin,

composer require zepgram/multi-threading  doesnt work

shoud be **composer require zepgram/module-multi-threading**
and we can  **composer require zepgram/module-multi-threading --ignore-platform-reqs**

You shoud change your readme.

Best regards,

Alex

**Comment by zepgram** [comment]
Hi Alex,

Did you install the php extension pcntl ?

Platform requirements are here to make sure that dependencies are installed.

**Comment by alexJouni** [comment]
Yes its already installed but i talk about your readme 
about composer require zepgram/multi-threading because maybe you have missed module prefix
shoud be  **composer require zepgram/module-multi-threading**   instead **composer require zepgram/multi-threading**,

**Comment by zepgram** [comment]
Oh alright, I didn't see that.

Thanks for reporting.
