### ISSUE TITLE
Iterating while emulating

### ISSUE THREAD

**Issue by pixiemediaweb** [zepgram/module-multi-threading#3]
Hi, thanks for this awesome module.  Hoping you can help.  I'm trying to implement it in a custom module to speed up a process we use to build frontend, store-specific product data for cache purposes. 

The function looks like this;
```

public function getProductCollectionHtml($collection, $storeId,$parallel=false) {
		
		if (empty($collection)) {
			return false;
		}

		$themeId = $this->scopeConfig->getValue(
			'design/theme/theme_id',
			\Magento\Store\Model\ScopeInterface::SCOPE_STORE,
			$storeId
		);
		
		$storeManager = $this->_storeManager;
		$design       = $this->design;
		$htmlReturn   = [];

		// Emulate the frontend 
		$this->appState->emulateAreaCode(\Magento\Framework\App\Area::AREA_FRONTEND, function () use (&$htmlReturn, $storeId, $themeId, $collection, $storeManager, $design, $parallel) {
			
			// Set the current store and design theme
			$storeManager->setCurrentStore($storeId); 
			$design->setDesignTheme($themeId);
			
			// Create and initialize the layout
			$layout = $this->layoutFactory->create();
			$layout->getUpdate()->addHandle('default');
			$layout->getUpdate()->addHandle('catalog_list_item');
			$layout->getUpdate()->load();
			$layout->generateXml();
			$layout->generateElements();
			
			// Find the product list item block
			$itemRendererBlock = $layout->getBlock('product_list_item');

			if ($itemRendererBlock) {
				
				$image         = 'new_products_content_widget_grid';
				$count         = 0;
				
				if(!$parallel) {
					echo 'parallel is false';
					foreach ($collection as $productId => $_product) {
						$count++;
						echo 'called: pid '.$productId.' with count '.$count.' || '.PHP_EOL;
						$phtml =  $someProcess();

						$htmlReturn[$productId] = $phtml;
					}
					
				} else {
					echo 'parallel is true!'; 
					echo 'Collection total is: '.count($collection); 
					$callback = function ($_product) use ($itemRendererBlock, &$htmlReturn, &$count) {
					$count++;
					$productId = $_product->getId();
					if(!isset($htmlReturn[$productId])) {
						
							echo 'called: pid '.$productId.' with count '.$count.' || '.PHP_EOL;
							$phtml = $someProcess();

							$htmlReturn[$productId] = $phtml;
					}
					
				};
				
				$this->forkedArrayProcessor->process(
					$collection,
					$callback,
					$pageSize = count($collection),
					$maxChildrenProcess = 250
				);
					
				}
				
				
				
			}
		});

		echo 'RETURNING htmlReturn'.PHP_EOL;
		return $htmlReturn;
	}
```

Toggling between parallel false or true, the overall processing time is roughly the same.   The parallel version appears faster in console output, but it does also repeat the same products for some reason.

The $collection is an array of [$product_id => $_product (object)]
 $someProcess() - just to simplify my code for you to read

I am slightly confused about the $pageSize variable, which ive tried setting to 1, 10, 100 and count($collection).   When its set to one I can see lots of new processing spinning up in htop, but the overall speed does not improve.  And the $count stays at 1 for a full round of all products before it starts counting up.  

So, what am i doing wrong? im not sure why using parallel is not making the process significantly quicker.

Any suggestions?

**Comment by zepgram** [comment]
Hi,

I didn't find the time to answer you before, and I'm not sure I'll be able to check this before next week. But I may help you concerning the parameters: you need to scale the processes based on the number of page by product your are processing.

For example, if you have 10 000 products.
If you define page size to 1000, and affect 10 processes, each process will be affected by a chunk of your array of 1000 products, and they will run in parallel.

If you have 10 000 products and you set a page size of 1, it means it will create a process for each product in your array, then it makes no sense to parallelizes it. It will take more time to create a process and killing it, than just execute the callback method by itself.
